---
# tasks file for linux_updates

- name: test if update_reboot is set correctly
  assert:
    that:
      - update_reboot is defined
    quiet: yesa

- name: update all software (dnf)
  dnf:
    name: "*"
    state: latest
  notify:
    - reboot
  when:
    - ansible_pkg_mgr == "dnf"

- name: configure yum
  block:
    - name: update all software (yum/6)
      yum:
        name: "*"
        state: latest
      notify:
        - reboot
      when:
        - ansible_distribution_major_version == "6"

    - name: configure 7
      block:
        - name: update all software (yum/7)
          yum:
            name: "*"
            state: latest
          notify:
            - reboot

        - name: install yum-utils
          package:
            name: yum-utils
      when:
        - ansible_distribution_major_version == "7"
  when:
    - ansible_pkg_mgr == "yum"
